spring.application.name=student
server.port=8081

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/java
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update

# Security
#spring.security.user.name=sam
#spring.security.user.password=MC5WdsFN3U9pK7FDuSMY5nA8XF6agDGYRc4AqkZ4

# JWT
jwt.secret=c2VjcmV0S2V5Rm9yVGhpc0FwcGxpY2F0aW9uTXVzdEJlQXRMZWFzdDI1NkJpdHNMb25n
jwt.expiration=86400000

# Eureka
#eureka.client.service-url.defaultZone=http://eureka:8761/eureka/